#!/usr/bin/make -f

myrelease != date +%F
myarch := amd64
myversion := 7.8
myflavour := efi-no_x11
myqcowname := openbsd-$(myflavour)-$(myrelease).qcow2
myqcowsigname := $(myqcowname).asc
mytemplatedir := /var/lib/vz/template/iso
mybuildroot := /tmp
myrepodir := software_repository/OpenBSD/$(myversion)/$(myarch)/

signify_keys = \
  /usr/share/signify-openbsd-keys/openbsd-78-base.pub \
  /usr/share/signify-openbsd-keys/openbsd-78-fw.pub \
  /usr/share/signify-openbsd-keys/openbsd-78-pkg.pub \
  /usr/share/signify-openbsd-keys/openbsd-78-syspatch.pub
